version: '3.8'

services:
  app:
    build: .
    container_name: ea-foods-preorder
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/database.sqlite  # Persist SQLite database
    restart: unless-stopped